#!/usr/bin/env python3
# outputs specified bit range for input addresses
# Author: Ahmad Yasin
# edited: Sep. 2021
#
from __future__ import print_function
__author__ = 'ayasin'

import common as C
import sys

# usage: addrbits left-index right-index [field=0] [prepend=0]
left = int(C.arg(1))
right = int(C.arg(2))
field = int(C.arg(3, '0'))
prepend = int(C.arg(4, '0'))

mask = 2**(left+1)-1

while True:
  line = sys.stdin.readline()
  if not line: break
  line = line.rstrip('\r\n')
  if line in ('--'):
    print(line)
    continue
  addr = int(C.str2list(line)[field], 16)
  bits = (addr & mask) >> right
  bits = '%02x'%bits
  print(bits, line) if prepend else print(bits)

