#!/usr/bin/env python
# stats on DSB misses
# Author: Ahmad Yasin
# edited: Sep. 2021
#
# usage: perf script -F +brstackinsn | ./dsb_miss
from __future__ import print_function
__author__ = 'ayasin'

import lbr
from common import ratio

c = {x: 0 for x in ('sequential', 'total')}
while True:
  sample = lbr.read_sample()
  if not sample: break
  assert len(sample) > 2, 'invalid sample: ' + str(sample)
  c['total'] += 1
  if not '#' in sample[-2]: c['sequential'] += 1

print(c, ratio('sequential', c))

