#!/usr/bin/env python3
# in-depth stats for a particular loop
# Author: Ahmad Yasin
# edited: May 2022
#
from __future__ import print_function
__author__ = 'ayasin'
import common as C

# usage: perf script -F +brstackinsn [--xed] | ./loop_stats ip-of-loop
loop = C.arg(1)
ev = C.arg(2, '-')
C.exe_cmd('%s/lbr_stats - %s 0 1 %s' % (C.dirname(), loop, ev))
