#!/usr/bin/env python
# outputs percentages & sum of number-prefixed inputs
# Author: Ahmad Yasin
# edited: March 2024
#
from __future__ import print_function
__author__ = 'ayasin'

import common as C
import sys

# usage: <ex: some-output | sort -n> | ptage

fmt = '{:5.%df}' % C.env2int('PTAGE_R', 1)
total, lines = 0, []
  
while True:
  line = sys.stdin.readline()
  if not line: break
  if not line.strip()[0].isdigit(): continue
  total += float(C.str2list(line)[0])
  lines.append(line)

for l in lines:
  n = float(C.str2list(l)[0])
  percent = fmt.format(100.0 * n/total) + '%'
  print(percent, l, end='')
 
print("  100%%\t%d\t\t\t===total"%int(total))

