#!/usr/bin/env python
# outputs percentages & sum of number-prefixed inputs
# Author: Ahmad Yasin
# edited: Sep. 2021
#
from __future__ import print_function
__author__ = 'ayasin'

import common as C
import sys

# usage: <ex: some-output | sort -n> | ptage

ptage_r = C.env2int('PTAGE_R')
total, lines = 0, []
  
while True:
  line = sys.stdin.readline()
  if not line: break
  if not line.strip()[0].isdigit(): continue
  total += float(C.str2list(line)[0])
  lines.append(line.rstrip('\r\n'))

for l in lines:
  n = float(C.str2list(l)[0])
  s = "%.1f%%\t" % (100.0*n/total)
  if ptage_r:
    s = '%s%%' % round(100.0*n/total, ptage_r)
  print(s + l)
 
print("100%%\t %d\t\t\t===total"%int(total))

