// Auto-generated by ayasin's gen-kernel.py version 0.86 invoked with:
// (unroll_factor=1, registers=16, registers_max=16, instructions=['vaddpd %ymm@,%ymm@,%ymm@'], loops=1, prolog_instructions=[], epilog_instructions=[], align=0, offset=0, label_prefix='Lbl', mode='basicblock', mode_args='', reference='MGM', init_regs=[], modify_regs=False)
// Do not modify!
//
/* fp-add-lat exposes the execution latency while fp-add-bw expose the throughput of a floating-point vector ADD instruction (e.g.)
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#define MSG "Reference: A Metric-Guided Method for Discovering Impactful Features and Architectural Insights for Skylake-Based Processors. Ahmad Yasin, Jawad Haj-Yahya, Yosi Ben-Asher, Avi Mendelson. TACO 2019 and HiPEAC 2020."

int main(int argc, const char* argv[])
{
    register uint64_t n asm ("r10");
    register uint64_t i0 asm ("r9");
    if (argc<2) {
        printf("%s: missing <num-iterations> arg!\n", argv[0]);
        exit(-1);
    }
    if (MSG) printf("%s\n", MSG ? MSG : "");
    asm ("      mov %1,%0"
                 : "=r" (n)
                 : "r" (atol(argv[1])));
    asm("	PAUSE");
    for (i0=0; i0<n; i0++) {
        asm("	vaddpd %ymm0,%ymm0,%ymm0");
        asm("	vaddpd %ymm1,%ymm1,%ymm1");
        asm("	vaddpd %ymm2,%ymm2,%ymm2");
        asm("	vaddpd %ymm3,%ymm3,%ymm3");
        asm("	vaddpd %ymm4,%ymm4,%ymm4");
        asm("	vaddpd %ymm5,%ymm5,%ymm5");
        asm("	vaddpd %ymm6,%ymm6,%ymm6");
        asm("	vaddpd %ymm7,%ymm7,%ymm7");
        asm("	vaddpd %ymm8,%ymm8,%ymm8");
        asm("	vaddpd %ymm9,%ymm9,%ymm9");
        asm("	vaddpd %ymm10,%ymm10,%ymm10");
        asm("	vaddpd %ymm11,%ymm11,%ymm11");
        asm("	vaddpd %ymm12,%ymm12,%ymm12");
        asm("	vaddpd %ymm13,%ymm13,%ymm13");
        asm("	vaddpd %ymm14,%ymm14,%ymm14");
        asm("	vaddpd %ymm15,%ymm15,%ymm15");
    }
    asm(".align 512; Lbl_end:");

    return 0;
}
