// Auto-generated by ayasin's gen-kernel.py version 0.74 invoked with:
// (align=0, epilog_instructions=[], instructions=['vmulpd %ymm@-1,%ymm@,%ymm@'], label_prefix='Lbl', loops=1, mode='basicblock', mode_args='', offset=0, prolog_instructions=[], reference='MGM', registers=16, registers_max=16, unroll_factor=10)
// Do not modify!
//
/* fp-add-lat exposes the execution latency while fp-add-bw expose the throughput of a floating-point vector ADD instruction (e.g.)
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#define MSG "Reference: A Metric-Guided Method for Discovering Impactful Features and Architectural Insights for Skylake-Based Processors. Ahmad Yasin, Jawad Haj-Yahya, Yosi Ben-Asher, Avi Mendelson. TACO 2019 and HiPEAC 2020."

int main(int argc, const char* argv[])
{
    uint64_t n;
    if (argc<2) {
        printf("%s: missing <num-iterations> arg!\n", argv[0]);
        exit(-1);
    }
    if (MSG) printf("%s\n", MSG ? MSG : "");
    n= atol(argv[1]);
    asm("	PAUSE");
    for (uint64_t i0=0; i0<n; i0++) {
        asm("	vmulpd %ymm15,%ymm0,%ymm0");
        asm("	vmulpd %ymm0,%ymm1,%ymm1");
        asm("	vmulpd %ymm1,%ymm2,%ymm2");
        asm("	vmulpd %ymm2,%ymm3,%ymm3");
        asm("	vmulpd %ymm3,%ymm4,%ymm4");
        asm("	vmulpd %ymm4,%ymm5,%ymm5");
        asm("	vmulpd %ymm5,%ymm6,%ymm6");
        asm("	vmulpd %ymm6,%ymm7,%ymm7");
        asm("	vmulpd %ymm7,%ymm8,%ymm8");
        asm("	vmulpd %ymm8,%ymm9,%ymm9");
        asm("	vmulpd %ymm9,%ymm10,%ymm10");
        asm("	vmulpd %ymm10,%ymm11,%ymm11");
        asm("	vmulpd %ymm11,%ymm12,%ymm12");
        asm("	vmulpd %ymm12,%ymm13,%ymm13");
        asm("	vmulpd %ymm13,%ymm14,%ymm14");
        asm("	vmulpd %ymm14,%ymm15,%ymm15");
        asm("	vmulpd %ymm15,%ymm0,%ymm0");
        asm("	vmulpd %ymm0,%ymm1,%ymm1");
        asm("	vmulpd %ymm1,%ymm2,%ymm2");
        asm("	vmulpd %ymm2,%ymm3,%ymm3");
        asm("	vmulpd %ymm3,%ymm4,%ymm4");
        asm("	vmulpd %ymm4,%ymm5,%ymm5");
        asm("	vmulpd %ymm5,%ymm6,%ymm6");
        asm("	vmulpd %ymm6,%ymm7,%ymm7");
        asm("	vmulpd %ymm7,%ymm8,%ymm8");
        asm("	vmulpd %ymm8,%ymm9,%ymm9");
        asm("	vmulpd %ymm9,%ymm10,%ymm10");
        asm("	vmulpd %ymm10,%ymm11,%ymm11");
        asm("	vmulpd %ymm11,%ymm12,%ymm12");
        asm("	vmulpd %ymm12,%ymm13,%ymm13");
        asm("	vmulpd %ymm13,%ymm14,%ymm14");
        asm("	vmulpd %ymm14,%ymm15,%ymm15");
        asm("	vmulpd %ymm15,%ymm0,%ymm0");
        asm("	vmulpd %ymm0,%ymm1,%ymm1");
        asm("	vmulpd %ymm1,%ymm2,%ymm2");
        asm("	vmulpd %ymm2,%ymm3,%ymm3");
        asm("	vmulpd %ymm3,%ymm4,%ymm4");
        asm("	vmulpd %ymm4,%ymm5,%ymm5");
        asm("	vmulpd %ymm5,%ymm6,%ymm6");
        asm("	vmulpd %ymm6,%ymm7,%ymm7");
        asm("	vmulpd %ymm7,%ymm8,%ymm8");
        asm("	vmulpd %ymm8,%ymm9,%ymm9");
        asm("	vmulpd %ymm9,%ymm10,%ymm10");
        asm("	vmulpd %ymm10,%ymm11,%ymm11");
        asm("	vmulpd %ymm11,%ymm12,%ymm12");
        asm("	vmulpd %ymm12,%ymm13,%ymm13");
        asm("	vmulpd %ymm13,%ymm14,%ymm14");
        asm("	vmulpd %ymm14,%ymm15,%ymm15");
        asm("	vmulpd %ymm15,%ymm0,%ymm0");
        asm("	vmulpd %ymm0,%ymm1,%ymm1");
        asm("	vmulpd %ymm1,%ymm2,%ymm2");
        asm("	vmulpd %ymm2,%ymm3,%ymm3");
        asm("	vmulpd %ymm3,%ymm4,%ymm4");
        asm("	vmulpd %ymm4,%ymm5,%ymm5");
        asm("	vmulpd %ymm5,%ymm6,%ymm6");
        asm("	vmulpd %ymm6,%ymm7,%ymm7");
        asm("	vmulpd %ymm7,%ymm8,%ymm8");
        asm("	vmulpd %ymm8,%ymm9,%ymm9");
        asm("	vmulpd %ymm9,%ymm10,%ymm10");
        asm("	vmulpd %ymm10,%ymm11,%ymm11");
        asm("	vmulpd %ymm11,%ymm12,%ymm12");
        asm("	vmulpd %ymm12,%ymm13,%ymm13");
        asm("	vmulpd %ymm13,%ymm14,%ymm14");
        asm("	vmulpd %ymm14,%ymm15,%ymm15");
        asm("	vmulpd %ymm15,%ymm0,%ymm0");
        asm("	vmulpd %ymm0,%ymm1,%ymm1");
        asm("	vmulpd %ymm1,%ymm2,%ymm2");
        asm("	vmulpd %ymm2,%ymm3,%ymm3");
        asm("	vmulpd %ymm3,%ymm4,%ymm4");
        asm("	vmulpd %ymm4,%ymm5,%ymm5");
        asm("	vmulpd %ymm5,%ymm6,%ymm6");
        asm("	vmulpd %ymm6,%ymm7,%ymm7");
        asm("	vmulpd %ymm7,%ymm8,%ymm8");
        asm("	vmulpd %ymm8,%ymm9,%ymm9");
        asm("	vmulpd %ymm9,%ymm10,%ymm10");
        asm("	vmulpd %ymm10,%ymm11,%ymm11");
        asm("	vmulpd %ymm11,%ymm12,%ymm12");
        asm("	vmulpd %ymm12,%ymm13,%ymm13");
        asm("	vmulpd %ymm13,%ymm14,%ymm14");
        asm("	vmulpd %ymm14,%ymm15,%ymm15");
        asm("	vmulpd %ymm15,%ymm0,%ymm0");
        asm("	vmulpd %ymm0,%ymm1,%ymm1");
        asm("	vmulpd %ymm1,%ymm2,%ymm2");
        asm("	vmulpd %ymm2,%ymm3,%ymm3");
        asm("	vmulpd %ymm3,%ymm4,%ymm4");
        asm("	vmulpd %ymm4,%ymm5,%ymm5");
        asm("	vmulpd %ymm5,%ymm6,%ymm6");
        asm("	vmulpd %ymm6,%ymm7,%ymm7");
        asm("	vmulpd %ymm7,%ymm8,%ymm8");
        asm("	vmulpd %ymm8,%ymm9,%ymm9");
        asm("	vmulpd %ymm9,%ymm10,%ymm10");
        asm("	vmulpd %ymm10,%ymm11,%ymm11");
        asm("	vmulpd %ymm11,%ymm12,%ymm12");
        asm("	vmulpd %ymm12,%ymm13,%ymm13");
        asm("	vmulpd %ymm13,%ymm14,%ymm14");
        asm("	vmulpd %ymm14,%ymm15,%ymm15");
        asm("	vmulpd %ymm15,%ymm0,%ymm0");
        asm("	vmulpd %ymm0,%ymm1,%ymm1");
        asm("	vmulpd %ymm1,%ymm2,%ymm2");
        asm("	vmulpd %ymm2,%ymm3,%ymm3");
        asm("	vmulpd %ymm3,%ymm4,%ymm4");
        asm("	vmulpd %ymm4,%ymm5,%ymm5");
        asm("	vmulpd %ymm5,%ymm6,%ymm6");
        asm("	vmulpd %ymm6,%ymm7,%ymm7");
        asm("	vmulpd %ymm7,%ymm8,%ymm8");
        asm("	vmulpd %ymm8,%ymm9,%ymm9");
        asm("	vmulpd %ymm9,%ymm10,%ymm10");
        asm("	vmulpd %ymm10,%ymm11,%ymm11");
        asm("	vmulpd %ymm11,%ymm12,%ymm12");
        asm("	vmulpd %ymm12,%ymm13,%ymm13");
        asm("	vmulpd %ymm13,%ymm14,%ymm14");
        asm("	vmulpd %ymm14,%ymm15,%ymm15");
        asm("	vmulpd %ymm15,%ymm0,%ymm0");
        asm("	vmulpd %ymm0,%ymm1,%ymm1");
        asm("	vmulpd %ymm1,%ymm2,%ymm2");
        asm("	vmulpd %ymm2,%ymm3,%ymm3");
        asm("	vmulpd %ymm3,%ymm4,%ymm4");
        asm("	vmulpd %ymm4,%ymm5,%ymm5");
        asm("	vmulpd %ymm5,%ymm6,%ymm6");
        asm("	vmulpd %ymm6,%ymm7,%ymm7");
        asm("	vmulpd %ymm7,%ymm8,%ymm8");
        asm("	vmulpd %ymm8,%ymm9,%ymm9");
        asm("	vmulpd %ymm9,%ymm10,%ymm10");
        asm("	vmulpd %ymm10,%ymm11,%ymm11");
        asm("	vmulpd %ymm11,%ymm12,%ymm12");
        asm("	vmulpd %ymm12,%ymm13,%ymm13");
        asm("	vmulpd %ymm13,%ymm14,%ymm14");
        asm("	vmulpd %ymm14,%ymm15,%ymm15");
        asm("	vmulpd %ymm15,%ymm0,%ymm0");
        asm("	vmulpd %ymm0,%ymm1,%ymm1");
        asm("	vmulpd %ymm1,%ymm2,%ymm2");
        asm("	vmulpd %ymm2,%ymm3,%ymm3");
        asm("	vmulpd %ymm3,%ymm4,%ymm4");
        asm("	vmulpd %ymm4,%ymm5,%ymm5");
        asm("	vmulpd %ymm5,%ymm6,%ymm6");
        asm("	vmulpd %ymm6,%ymm7,%ymm7");
        asm("	vmulpd %ymm7,%ymm8,%ymm8");
        asm("	vmulpd %ymm8,%ymm9,%ymm9");
        asm("	vmulpd %ymm9,%ymm10,%ymm10");
        asm("	vmulpd %ymm10,%ymm11,%ymm11");
        asm("	vmulpd %ymm11,%ymm12,%ymm12");
        asm("	vmulpd %ymm12,%ymm13,%ymm13");
        asm("	vmulpd %ymm13,%ymm14,%ymm14");
        asm("	vmulpd %ymm14,%ymm15,%ymm15");
        asm("	vmulpd %ymm15,%ymm0,%ymm0");
        asm("	vmulpd %ymm0,%ymm1,%ymm1");
        asm("	vmulpd %ymm1,%ymm2,%ymm2");
        asm("	vmulpd %ymm2,%ymm3,%ymm3");
        asm("	vmulpd %ymm3,%ymm4,%ymm4");
        asm("	vmulpd %ymm4,%ymm5,%ymm5");
        asm("	vmulpd %ymm5,%ymm6,%ymm6");
        asm("	vmulpd %ymm6,%ymm7,%ymm7");
        asm("	vmulpd %ymm7,%ymm8,%ymm8");
        asm("	vmulpd %ymm8,%ymm9,%ymm9");
        asm("	vmulpd %ymm9,%ymm10,%ymm10");
        asm("	vmulpd %ymm10,%ymm11,%ymm11");
        asm("	vmulpd %ymm11,%ymm12,%ymm12");
        asm("	vmulpd %ymm12,%ymm13,%ymm13");
        asm("	vmulpd %ymm13,%ymm14,%ymm14");
        asm("	vmulpd %ymm14,%ymm15,%ymm15");
    }
    asm(".align 512; Lbl_end:");

    return 0;
}
