// Auto-generated by ayasin's gen-kernel.py version 0.2 invoked with:
//  (align=14, instruction=['JMP'], mode='jumpy', num=5, offset=0) .
// Do not modify!
//
#include <stdio.h>
#include <stdlib.h>
#ifndef ITER
#define ITER 20000
#endif
int main(int argc, const char* argv[])
{
    long i,n;
    n= argv[1] ? atol(argv[1]) : ITER;
    asm("	PAUSE");
    for (i=0; i<n; i++) {
        asm("Lbl000:");
        asm("	JMP Lbl001");
        asm(".align 16384");
        asm("Lbl001:");
        asm("	JMP Lbl002");
        asm(".align 16384");
        asm("Lbl002:");
        asm("	JMP Lbl003");
        asm(".align 16384");
        asm("Lbl003:");
        asm("	JMP Lbl004");
        asm(".align 16384");
        asm("Lbl004:");
        asm("	JMP Lbl005");
        asm(".align 16384");
        asm("Lbl005:");
    }
    return 0;
}
