// Auto-generated by ayasin's gen-kernel.py version 0.6 invoked with:
//  (align=6, epilog_instructions=[], instructions=['NOP', 'NOP', 'test %rax,%rax', 'jle Lbl_end'], label_prefix='Lbl', mode='basicblock', num=1, offset=0, prolog_instructions=[], registers=0, registers_max=16) .
// Do not modify!
//
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#define MSG 0

int main(int argc, const char* argv[])
{
    uint64_t i,n;


    if (argc<2) {
        printf("%s: missing <num-iterations> arg!\n", argv[0]);
        exit(-1);
    }
    if (MSG) printf("%s\n", MSG ? MSG : "");
    n= atol(argv[1]);
    
    asm("	PAUSE");
        asm(".align 64");
    for (i=0; i<n; i++) {
        asm("	NOP");
        asm("	NOP");
        asm("	test %rax,%rax");
        asm("	jle Lbl_end");
    }
    asm(".align 512; Lbl_end:");


    return 0;
}
