// Auto-generated by ayasin's gen-kernel.py version 0.2 invoked with: (align=0, instruction=['addps %xmm1,%xmm2', 'vsubps %ymm1,%ymm2,%ymm3'], mode='basicblock', num=10, offset=0)
// Do not modify!
//
#include <stdio.h>
#include <stdlib.h>

int main(int argc, const char* argv[])
{
    long i,n;
    if (argc<2) {
        printf("%s: missing <num-iterations> arg!\n", argv[0]);
        exit(-1);
    }
    n= atol(argv[1]);
    asm("	PAUSE");
    for (i=0; i<n; i++) {
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
    }
    return 0;
}

