// Auto-generated by ayasin's gen-kernel.py version 0.86 invoked with:
// (unroll_factor=10, registers=0, registers_max=16, instructions=['addps %xmm1,%xmm2', 'vsubps %ymm1,%ymm2,%ymm3'], loops=1, prolog_instructions=[], epilog_instructions=[], align=0, offset=0, label_prefix='Lbl', mode='basicblock', mode_args='', reference=None, init_regs=[], modify_regs=False)
// Do not modify!
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#define MSG 0

int main(int argc, const char* argv[])
{
    register uint64_t n asm ("r10");
    register uint64_t i0 asm ("r9");
    if (argc<2) {
        printf("%s: missing <num-iterations> arg!\n", argv[0]);
        exit(-1);
    }
    if (MSG) printf("%s\n", MSG ? MSG : "");
    asm ("      mov %1,%0"
                 : "=r" (n)
                 : "r" (atol(argv[1])));
    asm("	PAUSE");
    for (i0=0; i0<n; i0++) {
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
        asm("	addps %xmm1,%xmm2");
        asm("	vsubps %ymm1,%ymm2,%ymm3");
    }
    asm(".align 512; Lbl_end:");

    return 0;
}
